const mockData = {
  exercises: [
    {
      id: 1,
      title: 'BARBELL DEADLIFT',
      description: '<p><strong>Step 1:</strong> Stand in athletic posture with feet hip to shoulder width apart and toes pointing forward. Hinge at the hips and slightly bend the knees to grab onto the barbell with hands slightly wider than shins. Brace the abs and position the bar over midfoot.</p><p><strong>Step 2:</strong> With the back flat and bar close to the shins and thigh, push into the floor to lift the bar. Maintain the head and torso angle until the bar passes the knees then stand upright.</p><p><strong>Step 3:</strong> Reverse the pattern, hinging at the hips to initiate, to return the bar to its starting position.</p><p><strong>Step 4:</strong> Repeat for the desired number of repetitions. <strong>Avoid</strong> rounding the spine, over emphasizing the knee bend, losing head position or rounding the shoulders.</p>',
      category: 'Glutes, Hamstrings, Quads, Glutes',
      equipment: 'Barbell',
      difficulty: 'Intermediate',
      bodyPart: ['Glutes', 'Hamstrings', 'Quads'],
      image: 'https://www.nasm.org/images/nasmlibraries/nasm-resource-center/guides/squats-and-deadlifts.jpg',
      videoUrl: '#',
    },
    {
      id: 2,
      title: 'KETTLEBELL DEADLIFT',
      description: '<p>A fundamental movement pattern that targets the posterior chain muscles while teaching proper hip hinge mechanics.</p>',
      category: 'Glutes, Hamstrings, Quads, Glutes',
      equipment: 'Kettlebell',
      difficulty: 'Beginner',
      bodyPart: ['Quadriceps', 'Hamstrings', 'Glutes'],
      image: 'https://www.nasm.org/images/nasmlibraries/nasm-resource-center/guides/squats-and-deadlifts.jpg',
      videoUrl: '#',
    },
    {
      id: 3,
      title: 'DUMBBELL ROMANIAN DEADLIFT',
      description: '<p>A hip-dominant exercise that emphasizes the eccentric portion of the movement to target the hamstrings and glutes.</p>',
      category: 'Hamstrings, Glutes, Glutes',
      equipment: 'Dumbbells',
      difficulty: 'Intermediate',
      bodyPart: ['Hamstrings', 'Glutes'],
      image: 'https://www.nasm.org/images/nasmlibraries/nasm-resource-center/guides/squats-and-deadlifts.jpg',
      videoUrl: '#',
    },
    {
      id: 4,
      title: 'LYING LEG CURL',
      description: '<p>An isolation exercise that targets the hamstrings through knee flexion while lying prone.</p>',
      category: 'Hamstrings, Calves',
      equipment: 'Lying Leg Curl Machine',
      difficulty: 'Beginner',
      bodyPart: ['Hamstrings', 'Calves'],
      image: 'https://www.nasm.org/images/nasmlibraries/nasm-resource-center/guides/squats-and-deadlifts.jpg',
      videoUrl: '#',
    },
    {
      id: 5,
      title: 'BARBELL BICEP CURL',
      description: '<p>A classic arm exercise that targets the biceps through elbow flexion using a barbell.</p>',
      category: 'Biceps',
      equipment: 'Barbell',
      difficulty: 'Beginner',
      bodyPart: ['Biceps'],
      image: 'https://www.nasm.org/images/nasmlibraries/nasm-resource-center/guides/squats-and-deadlifts.jpg',
      videoUrl: '#',
    },
    {
      id: 6,
      title: 'FLOOR BRIDGE',
      description: '<p>A foundational exercise that targets the glutes and core while teaching proper hip extension.</p>',
      category: 'Core, Glutes, Glutes',
      equipment: 'None',
      difficulty: 'Beginner',
      bodyPart: ['Core', 'Glutes'],
      image: 'https://www.nasm.org/images/nasmlibraries/nasm-resource-center/guides/squats-and-deadlifts.jpg',
      videoUrl: '#',
    },
    {
      id: 7,
      title: 'FLOOR PRONE COBRA',
      description: '<p>A back extension exercise that strengthens the posterior chain and improves spinal extension.</p>',
      category: 'Back, Shoulders',
      equipment: 'None',
      difficulty: 'Beginner',
      bodyPart: ['Back', 'Shoulders'],
      image: 'https://www.nasm.org/images/nasmlibraries/nasm-resource-center/guides/squats-and-deadlifts.jpg',
      videoUrl: '#',
    },
    {
      id: 8,
      title: 'GOOD MORNINGS',
      description: '<p>A hip hinge movement that targets the posterior chain with emphasis on the lower back and hamstrings.</p>',
      category: 'Hamstrings, Glutes',
      equipment: 'Barbell',
      difficulty: 'Intermediate',
      bodyPart: ['Hamstrings', 'Glutes'],
      image: 'https://www.nasm.org/images/nasmlibraries/nasm-resource-center/guides/squats-and-deadlifts.jpg',
      videoUrl: '#',
    },
  ],
  categories: {
    bodyPart: [
      { id: 'abdominals', name: 'Abdominals' },
      { id: 'biceps', name: 'Biceps' },
      { id: 'back', name: 'Back' },
      { id: 'chest', name: 'Chest' },
      { id: 'core', name: 'Core' },
      { id: 'glutes', name: 'Glutes' },
      { id: 'hamstrings', name: 'Hamstrings' },
      { id: 'quadriceps', name: 'Quadriceps' },
      { id: 'shoulders', name: 'Shoulders' },
    ],
    equipment: [
      { id: 'none', name: 'Body Weight' },
      { id: 'barbell', name: 'Barbell' },
      { id: 'dumbbells', name: 'Dumbbells' },
      { id: 'kettlebell', name: 'Kettlebell' },
      { id: 'cable', name: 'Cable' },
      { id: 'lying-leg-curl-machine', name: 'Machine' },
    ],
    difficulty: [
      { id: 'beginner', name: 'Beginner' },
      { id: 'intermediate', name: 'Intermediate' },
      { id: 'advanced', name: 'Advanced' },
    ],
  },
};

export default mockData;
